package com.jzp.mapper;

import com.jzp.dataobject.Order;
import org.springframework.stereotype.Repository;

@Repository
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_information
     *
     * @mbg.generated Mon Jun 08 09:50:45 CST 2020
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_information
     *
     * @mbg.generated Mon Jun 08 09:50:45 CST 2020
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_information
     *
     * @mbg.generated Mon Jun 08 09:50:45 CST 2020
     */
    Order selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_information
     *
     * @mbg.generated Mon Jun 08 09:50:45 CST 2020
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_information
     *
     * @mbg.generated Mon Jun 08 09:50:45 CST 2020
     */
    int updateByPrimaryKey(Order record);
}