package com.jzp.mapper;

import com.jzp.dataobject.Sequence;
import org.springframework.stereotype.Repository;

@Repository
public interface SequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 08 08:49:55 CST 2020
     */
    int insert(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 08 08:49:55 CST 2020
     */
    int insertSelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 08 08:49:55 CST 2020
     */
    Sequence selectByPrimaryKey(String name);

    Sequence getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 08 08:49:55 CST 2020
     */
    int updateByPrimaryKeySelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 08 08:49:55 CST 2020
     */
    int updateByPrimaryKey(Sequence record);
}