package com.jzp.mapper;

import com.jzp.dataobject.User;
import org.springframework.stereotype.Repository;

@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_information
     *
     * @mbg.generated Sat Jun 06 20:52:47 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_information
     *
     * @mbg.generated Sat Jun 06 20:52:47 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_information
     *
     * @mbg.generated Sat Jun 06 20:52:47 CST 2020
     */
    User selectByPrimaryKey(Integer id);

    /**
     * 根据用户 telephone 查询用户信息
     */
    User selectByTelephone(String telephone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_information
     *
     * @mbg.generated Sat Jun 06 20:52:47 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_information
     *
     * @mbg.generated Sat Jun 06 20:52:47 CST 2020
     */
    int updateByPrimaryKey(User record);
}