package com.jzp.dataobject;

public class Sequence {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.name
     *
     * @mbg.generated Mon Jun 08 08:49:55 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.current_value
     *
     * @mbg.generated Mon Jun 08 08:49:55 CST 2020
     */
    private Integer currentValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.step
     *
     * @mbg.generated Mon Jun 08 08:49:55 CST 2020
     */
    private Integer step;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.name
     *
     * @return the value of sequence.name
     *
     * @mbg.generated Mon Jun 08 08:49:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.name
     *
     * @param name the value for sequence.name
     *
     * @mbg.generated Mon Jun 08 08:49:55 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.current_value
     *
     * @return the value of sequence.current_value
     *
     * @mbg.generated Mon Jun 08 08:49:55 CST 2020
     */
    public Integer getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.current_value
     *
     * @param currentValue the value for sequence.current_value
     *
     * @mbg.generated Mon Jun 08 08:49:55 CST 2020
     */
    public void setCurrentValue(Integer currentValue) {
        this.currentValue = currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.step
     *
     * @return the value of sequence.step
     *
     * @mbg.generated Mon Jun 08 08:49:55 CST 2020
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.step
     *
     * @param step the value for sequence.step
     *
     * @mbg.generated Mon Jun 08 08:49:55 CST 2020
     */
    public void setStep(Integer step) {
        this.step = step;
    }
}